# Generated by Django 3.2.3 on 2021-05-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20210520_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='end_time',
            field=models.TimeField(blank=True, default='17:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='meeting_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='start_time',
            field=models.TimeField(blank=True, default='08:00:00', null=True),
        ),
    ]
